language: python

python:
  - '3.4'
  - '2.7'

env:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0

before_install:
  - sudo apt-get install -y espeak python-espeak
  - sudo apt-get install -y dbus python-dbus python-dbus-dev
  - sudo apt-get install -y jackd2

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - nosetests  --with-coverage --cover-package=dialogflow

after_success:
  - coveralls
